//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DYC_project
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssignTask
    {
        public int Id { get; set; }
        public string WorkerName { get; set; }
        public string WorkerPhoneNumber { get; set; }
        public string ComplainId { get; set; }
        public string ComplainDetails { get; set; }
    }
}
